---
title: "Neuro Researchers"
date: "`r paste0('Updated: ', Sys.Date())`"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    # theme: cerulean
    css: theme-neuro.css
    highlight: tango  # specifies the syntax highlighting style
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(flexdashboard)
library(DT)
# df <- readxl::read_xlsx("../data/tutkijat.xlsx")
# dat <- df #[,c(1,2,4,5,16,31)]
dat <- df %>% 
  dplyr::mutate(Name = paste(`Last name`, `First name`),
                Publish= tolower(`Publish`),
                `Link 1 (Research group website)` = NULL,
                `Link 2 (Research portal)` = NULL,
                `Link 3 (Clinical researcher website)` = NULL,
                `Link 4 (Other website)` = NULL,
                `Last name` <- NULL,
                `First name` <- NULL,
                `Key words` = tolower(`Key words`)) %>% 
  dplyr::filter(Publish == "yes") %>%
  dplyr::rename(
                `Faculty / Field of expertise` = Faculty,
                Keywords = `Key words`,
                `Web page` = Linkki) 

# orgmembers <- c("Aalto University", "HUS", "University of Helsinki", "University of Eastern Finland", "University of Jyväskylä", "University of Oulu", "Tampere University Hospital", "Tampere University", "University of Turku", "Oulu University Hospital", "Kuopio University Hospital",  "Turku University Hospital")
# dat$Organization <- ifelse(Organization %in% orgmembers, Organization, "Other")

dat$Organization <- as.factor(dat$Organisation)
# dat$Tiedekunta <- as.factor(dat$Tiedekunta)
dat <- dat[, c("Name", "Organization", "Faculty / Field of expertise", "Keywords", "Web page")]
dat <- dat[order(dat$Name),]


```


Search
=======================================================================

Row
-----------------------------------------------------------------------

### Researchers

```{r}
valueBox(nrow(dat), icon = "fa-user")
```

### Organizations

```{r}
valueBox(length(unique(dat$Organization)), icon = "fa-building")
```

### Faculties

```{r}
valueBox(length(unique(dat$`Faculty / Field of expertise`)), icon = "fa-sitemap")
```



Row
-----------------------------------------------------------------------


```{r datatable}
DT::datatable(dat,
              selection = c("single"),
              rownames = FALSE, 
              filter = 'top',
              escape = FALSE,
              #extensions = 'Buttons', 
              options = list(
                # order = list(list(0, 'desc'), list(2, 'asc')),
                # dom = 'Bfrtip',
                search = list(regex = TRUE, caseInsensitive = TRUE),
                columnDefs = list(list(className = 'dt-left',  targets = "_all")),
                pageLength = 20
                # language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Finnish.json')
                # dom = 'Bfrtip',
                # buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
              )) 

```

About
=======================================================================




